import Head from "next/head";
import React from "react";
import Header from "./header";

interface LayoutProps {
  children: React.ReactNode;
  center?: boolean;
}

const Layout = ({ children, center }: LayoutProps) => {
  return (
    <div className="bg-black min-h-screen text-white">
      <Head>
        <title>DEKT.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main
        className={`${center && "flex flex-col justify-center items-center"}`}
        style={{
          minHeight: "calc(100vh - 3rem)",
        }}
      >
        {children}
      </main>
    </div>
  );
};

export default Layout;
